### PR TITLE
Add Digital Sky Public APIs Spec v1

### PR DESCRIPTION
**Pull request by not-vibhu**

### CODE REVIEW

**Review by hrishiballal — CHANGES_REQUESTED** [review]
We need to make sure we have the latest version every time this is updated, where is the original file located? Can we link to that instead of having a copy of the file? This way we don't have to worry about maintaining it every time there are changes to the original file

**Comment by not-vibhu** [comment]
The file is located at 
https://digitalsky.dgca.gov.in/assets/files/DigitalSky-Public-API-Swagger-Specification-v1.0.0.yml 

But I'm not sure whether this location and filename would remain the same in future updates.

**Comment by hrishiballal** [comment]
I agree, but can I request we link it to the DGCA one for the moment, we can keep a copy and once the DGCA one bombs / expires, we can add it please. Just because in case they change the API and we are implementing the "old one" it won't work.

**Comment by not-vibhu** [comment]
Sure, I'll make the changes

**Pull request closed without merging**
